### ISSUE TITLE
Mod tasks in progress window pops up and stays on top

### ISSUE THREAD

**Issue by Cooliosity** [ramensoftware/windhawk#102]
Sometimes, the window that can be seen in the image pops up out of nowhere and just stays there for a while. Sometimes it disappears after a minute, sometimes it stays for longer. What bugs me the most about this window is, that it just stays on top even when unfocused, with no way to remove it. Unfortunately I was too slow this time and wasn't able to find out which process the PID is from, I will make sure to find it out next time and report back here. I have no other mods installed except slick window arrangement.

![image](https://github.com/ramensoftware/windhawk-mods/assets/15091187/61f08c60-1ef6-4c6f-bbb7-f0d2691c018f)

**Comment by Cooliosity** [comment]
Alright, the issue finally happened again. 
This is what the Windhawk window shows
![Screenshot 2023-09-24 231116](https://github.com/ramensoftware/windhawk/assets/15091187/091aa5f6-6e0c-4021-bd63-3abf53782243)

And this is what task manager shows
![image](https://github.com/ramensoftware/windhawk/assets/15091187/6e49d31f-cc79-4570-b729-84e3180471c9)

Could it be related to the process being suspended? There are only 3 other Suspended processes in my task manager, all of them are from Microsoft
![image](https://github.com/ramensoftware/windhawk/assets/15091187/b24ffcf3-7a8f-4855-8f76-11e4e68139a8)

**Comment by m417z** [comment]
I believe that it is related, and that the following happens:
* WhatsApp (or another suspendable process) launches
* Windhawk prepares to load the relevant mods
  * "Initializing..." is shown
* Windows decides to suspend WhatsApp
* Windhawk still waits for the mods to initialize, so "Initializing..." is still shown
* Whenever Windows decides to resume WhatsApp, the mods finally load and the message goes away, but it can take a long time

I have a fix in mind which will take the process state into account, and I plan on implementing it for the next Windhawk version.

**Comment by m417z** [comment]
Version 1.4 doesn't display the progress popup for suspended processes, so this should no longer be an issue.

**Comment by Cooliosity** [comment]
I am glad you were able to resolve this issue, keep up the good work!

**Comment by redactedscribe** [comment]
Also seeing this pop-up in v 1.4.1.

Happens predictably each time I'm using another software (WingetUI) to export its settings to a local file. After I browse to the path and press Save, moments later I see this pop up (unexpected), sometimes twice in a row, then disappears before File Explorer reveals itself at the path I chose (expected).

![windhawk_2024-01-18_13-06-32](https://github.com/ramensoftware/windhawk/assets/25013746/1dcbb255-34f2-493b-9a4b-24db48f3b7a6)

I'm assuming I shouldn't see this pop-up at all.

I have these mods installed:

- Cycle taskbar buttons with mouse wheel: Enabled
- Taskbar Volume Control (disabled)

**Comment by m417z** [comment]
@redactedscribe that's a different problem than what's described in the original issue. Since the mod doesn't work, perhaps it tries to download the symbols each time and fails. In this case, I think the popup is a good thing as it explains the delay in opening explorer and shows that there's something that doesn't work.

Please attach debug logs by following the instructions on the Troubleshooting page:
https://github.com/ramensoftware/windhawk/wiki/Troubleshooting#some-or-all-windhawk-mods-dont-work

> * Disable the mod.
> * Go to the mod's Advanced tab.
> * Set **Debug logging** to **Detailed debug logs**.
> * Click on **Show log output**.
> * Enable the mod.
> * Verify that the mod doesn't work, copy the log and save it to a file.
> * Set **Debug logging** back to **None**.

**Comment by redactedscribe** [comment]
Thank you for the quick response. Your comment looked like the solution: A simple firewall issue. File Explorer needs access to `*.blob.core.windows.net` and `msdl.microsoft.com` for symbols to download.

![windhawk_2024-01-18_13-39-01](https://github.com/ramensoftware/windhawk/assets/25013746/9cfc735e-3655-4d06-b91c-44408127cf1b)

Unfortunately, the windows still do not scroll. I will open an issue or provide the answer here if I resolve this.

**Comment by m417z** [comment]
The mod indeed only supports the new Windows 11 taskbar. As mentioned in the mod's description, the 7+ Taskbar Tweaker tool can be used to achieve this functionality with the old taskbar.

**Comment by redactedscribe** [comment]
Switched to the Windows 11 taskbar to test and it does indeed work with that. However I'll have to forgo this mod as I would like the Win 10 style because I can drag it to my other screen. Thanks for your help.

**Comment by N0VA-The-Git-User** [comment]
Having a similar issue

![image](https://github.com/ramensoftware/windhawk/assets/145279552/a1eddc3f-7400-4077-844f-b9f490e56315)

here are the debug logs:

P.S.  Good F***in luck


[dear-god.txt](https://github.com/user-attachments/files/15845780/dear-god.txt)

**Comment by kosei9987aaa** [comment]
same issue

**Comment by whyudothis5656** [comment]
Same issue March 2025

**Comment by prochan2** [comment]
Same issue April 2025

**Comment by LazytownSpo666** [comment]
How do i disable it? There is no option.

**Comment by m417z** [comment]
> How do i disable it? There is no option.

It's possible to configure the time after which the dialog is displayed. Setting a long time will make its appearance less common.

![Image](https://github.com/user-attachments/assets/ac6fd8b5-1f57-41ef-bbfb-ba9b908d92cc)

The number means: how long to wait until the dialog is shown. Meaning, you'd want a bigger number, not a smaller number, to see the dialog less often. For example, you can set it to 30000 to have the dialog shown only for operations that run more than 30 seconds.

But note that it's not a proper fix, it's a workaround at best, sweeping the problem under the rug.

Can you please collect logs to help me understand the reason for the delay and for the popup being shown?

Please try this for any of the mods which is displayed in the popup:

* Enable the mod.
* Go to the mod's Advanced tab.
* Set **Debug logging** to **Detailed debug logs**.
* Click on **Show log output**.
* Run various programs until the popup shows up.
* When the popup is shown, notice which process is shown in the popup, or just make a screenshot of it.
* Copy the log and save it to a file.
* Set **Debug logging** back to **None**.

Attach the log file and the process name/screenshot here. Thanks.

**Comment by m417z** [comment]
@BafflingSpy3294 I'm glad it helped, but as I said, it doesn't fix the underlying issue. I'm trying to get a better understanding of the problem, but so far I couldn't get anyone in any of the threads to share additional information.

Can you please address the second part of my previous message? Thanks.

**Comment by BafflingSpy3294** [comment]
@m417z No problem! ^^

**Comment by gabiballetje** [comment]
Still having this issue regularly. Still have not found a way to get rid of it or anything. It's extremely annoying, all that works is restarting my PC

**Comment by m417z** [comment]
@gabiballetje please provide more details. Which mod and process are listed? The latest version of Windhawk has some improvements to make it less likely, even if there's a mod issue or incompatibility.

**Comment by gabiballetje** [comment]
Also slick-window-arrangement.
And i think also that it is re-enabling i think.

**Comment by m417z** [comment]
Please post a screenshot.

**Comment by gabiballetje** [comment]
Well, I’ll have to wait until it happens again then XD
