### ISSUE TITLE
Interfering with other programs

### ISSUE THREAD

**Issue by PrinceOC912** [ramensoftware/windhawk#104]
When windhawk is running, even without any mods installed, a specific extension (ff2mpv) on both chrome and Firefox doesn't work and it only works when I exit windhawk. There are also some programs that won't open when windhawk is opened but that happens occasionally and I couldn't reproduce the issue.

Edit: Excluding all processes and including explorer and chrome (the processes I have mods installed for) seems to fix the extension issue.

**Comment by m417z** [comment]
It took me a while to set it up, but finally, it did work with or without Windhawk. Do you have an antivirus? Perhaps it causes this issue due to Windhawk's code injection.

https://github.com/ramensoftware/windhawk/assets/4129781/b3b445eb-9c17-4af5-a364-90d5754afee5

**Comment by PrinceOC912** [comment]
I have an antivirus yes (Eset Internet Security), but I went through the log and it doesn't seem to be blocking anything related to Windhawk. Even after completely disabling protection the extension still doesn't work unless I exclude everything but chrome, firefox and explorer.exe so I don't know what could be the issue, but it isn't a bother since all the mods I use still work with full functionality and I haven't encountered any problems so far.

**Comment by m417z** [comment]
I still suspect ESET, especially due to the "some programs that won't open when windhawk is opened" part. There was a similar report in the Discord channel and ESET was involved there, too. If that's the case, there's not much that can be done on Windhawk's part.

In any case, since it's no longer a problem, and I don't see what else can be done without additional extensive checks, I'm closing this issue.

**Comment by LinuxOnTheDesktop** [comment]
> I still suspect ESET, especially due to the "some programs that won't open when windhawk is opened" part. There was a similar report in the Discord channel and ESET was involved there, too. If that's the case, there's not much that can be done on Windhawk's part.

I have ESET, and I find that Firefox opens from the taskbar on Windows 11 only every time - _**until** I add Firefox to Windhawk's excluded processes._
