### ISSUE TITLE
Windhawk v1.3.1 beta Windows Explorer.exe Crash

### ISSUE THREAD

**Issue by soulcollectivex** [ramensoftware/windhawk#109]
Windhawk v1.3.1 beta causes the Windows file explorer to become inaccessible when the setting "Inject into critical system processes" is turned on (required for a mod to work) only after updating my copy of Windows 10 Pro to this update:
2023-09 Cumulative Update Preview for Windows 10 Version 22H2 for x64-based Systems (KB5030300)
I have followed all the troubleshooting steps and I receive this error even if I do not have any programs running in my system tray other than windhawk, I have also disabled windows defender as that is my only antivirus on my pc, it happens with defender on or even without it on. 
This issue only occurs when this setting is tuned on in windhawk... if it is disabled, explorer windows launch and function normally.
I'm still new to reporting bugs on GitHub, but I thought it might be important to mention...
I have left a screenshot below of the error I am receiving when the "Inject into critical system processes" setting is turned on, and I try opening a folder or file explorer window. Thanks.

<img width="280" alt="error Screenshot 2023-10-01 010739" src="https://github.com/ramensoftware/windhawk/assets/126836951/4d265fb1-6578-4bb5-83c2-9a0336454b3d">

**Comment by m417z** [comment]
Are any mods enabled? Are you getting this error when all mods are disabled?

**Comment by soulcollectivex** [comment]
So I have deduced that the problem may be a combination of mods I am using, but I cannot figure out which combination of mods were causing the issue. I seemed to have partially solved the issue though, as it looks like it has been caused by the mod "dark mode for notepad" and some other mods in tandem with it, because it still occurred when just disabling the mod, but after completely removing it the issue seems to have disappeared but randomly re-appears and then resolves itself after trying to open an explorer window. So I am just removing all the mods I have installed and seeing what works.

**Comment by m417z** [comment]
"dark mode for notepad" only affects notepad, so it shouldn't affect explorer. In the next Windhawk version, I plan on making these kinds of issues less likely by limiting mods that target all processes to non-system targets, unless those mods explicitly ask for specific system targets, or unless configured otherwise in Windhawk's settings.

**Comment by soulcollectivex** [comment]
Thanks for your assistance, and for making such a cool customization program.

**Comment by soulcollectivex** [comment]
Thanks for your assistance, and for making such a cool customization program.
