### ISSUE TITLE
Please release new version

### ISSUE THREAD

**Issue by Anixx** [ramensoftware/windhawk#114]
It came to be known that Windhawk has a bug with symbols download for 32-bit programs.

There is a workaround (self-fix) mod, but it really does not work well, slowing down the system and displaying download dialog window at random times.

Thus, many mods essentially can be used only for 64-bit programs.

If the fix is already in the tree (which it is, I hope), please release the newer version, this change alone is very valuable.

**Comment by m417z** [comment]
Done.

**Comment by Anixx** [comment]
Congratulations! We have got 5 new mods (so far) in the official repo due to this update only.
