### ISSUE TITLE
In Menu Style Visibility: Compact the menu button is not visible

### ISSUE THREAD

**Issue by Anixx** [ramensoftware/windhawk#117]
This is the default setting, but the menu is not accessible at all as the menu button is not visible

**Comment by m417z** [comment]
Copying from my other comment:

The menu is supposed to be hidden. What's missing without the menu?

Regarding "Select all", where is it useful?

**Comment by Anixx** [comment]
Select all is necessary when for instance I create a new mod and want to delete the example thumb. Or when I want to copy the entire mod into a new file so to make a new mod based on the previous one.

Without menu, how to save or load a file?

**Comment by Anixx** [comment]
* Change zoom level

**Comment by Anixx** [comment]
Default zoom level is evidently intended for touchscreens, it is gigantic and the list of all mods does not fit the screen.

**Comment by m417z** [comment]
Please, let's not post the same comments on several issues. Let's focus on menu-related questions here. 

For selecting all code while in development mode, it would make sense to have it in the right click menu, but Microsoft decided not to add it, we discussed that:
https://github.com/ramensoftware/windhawk/discussions/55#discussioncomment-5495511
Also, I thought developers would just use Ctrl+A.

For loading and saving a file, it's not supported, and I don't know what the menu does but possibly not what you expect, so it's a good thing that you don't have it.

For zoom, you can use Ctrl + and Ctrl -.
