### ISSUE TITLE
When the "Native" style option is on, the menus use non-native style

### ISSUE THREAD

**Issue by Anixx** [ramensoftware/windhawk#118]
Some kind of white theme is used instead of the native theme:

![изображение](https://github.com/ramensoftware/windhawk/assets/1271736/e2573a8f-2371-4652-8e57-9deaf84e2170)

**Comment by Anixx** [comment]
I don't have VSCode, but probably yes. All this idea of using browser interface for desktop programs is absolutely fishy and buggy. I can report a ton of bug reports regarding the appearance.

**Comment by Anixx** [comment]
They have 8000 bug reports open...

**Comment by m417z** [comment]
It has pros and cons, but that's what I decided to use for Windhawk. All programs have bugs, more complex programs tend to have more bugs, and an IDE is a complex program.

Regarding this specific issue, sorry, but it's a very low priority to fix for Windhawk.

**Comment by aubymori** [comment]
> Some kind of white theme is used instead of the native theme:
> 
> ![изображение](https://user-images.githubusercontent.com/1271736/275663023-e2573a8f-2371-4652-8e57-9deaf84e2170.png)

These are default Chromium menus. This is just how menus look with native titlebar enabled in VSCode. This is a non-issue and should be closed.

**Comment by m417z** [comment]
Whether it's an issue or a feature request, I don't plan addressing it, so I agree that closing it is a good idea.
