### ISSUE TITLE
virustotal detects by two vendors

### ISSUE THREAD

**Issue by JuraLys** [ramensoftware/windhawk#119]
see https://www.virustotal.com/gui/url/5c075f2284d6c5d2f88790dc2a379eca0eed1fba7cd4d471ff96cc5b6264f332?nocache=1
![image](https://github.com/ramensoftware/windhawk/assets/146434286/18009229-c552-4262-9897-8d0374c2e764)

**Comment by m417z** [comment]
These are false positive decisions. Unfortunately, false positive detections are a never ending problem. False detections like these were reported many times by users. Here's one of the recent discussions about it, one of dozens:
https://ramensoftware.com/7-taskbar-tweaker/comment-page-51#comment-13213

<p>Windhawk injects code into other programs, and antiviruses often find it suspicious. The "Malware" label is grossly wrong, but it's unfortunately <a href="https://blog.nirsoft.net/2009/05/17/antivirus-companies-cause-a-big-headache-to-small-developers/" rel="nofollow ugc">common for antiviruses</a> to incorrectly detect software which is not very popular as malicious.</p>

**Comment by m417z** [comment]
These are false positive detections. Unfortunately, false positive detections are a never ending problem. False detections like these were reported many times by users. Here's one of the recent discussions about it, one of dozens:
https://ramensoftware.com/7-taskbar-tweaker/comment-page-51#comment-13213

<p>Windhawk injects code into other programs, and antiviruses often find it suspicious. The "Malware" label is grossly wrong, but it's unfortunately <a href="https://blog.nirsoft.net/2009/05/17/antivirus-companies-cause-a-big-headache-to-small-developers/" rel="nofollow ugc">common for antiviruses</a> to incorrectly detect software which is not very popular as malicious.</p>

**Comment by m417z** [comment]
FWIW the latest Windhawk version has one detection:
https://www.virustotal.com/gui/file/fb1ecc8b6eeebda10fa06c1c5dce004e53ff17288929c0e77a0daaa384d2edf4

You can help by reporting Windhawk as a false positive to the relevant antivirus companies. Other than that, there's not much that can be done, so I'm closing this issue.
