### ISSUE TITLE
Language pack is unavailable after installing

### ISSUE THREAD

**Issue by Ne0niq** [ramensoftware/windhawk#12]
Hi, dear author. Thanks for making such interesting software.

Well, as title says... Program suggested me to download Russian language pack and restart, I agreed and nothing happened after Windhawk restart. No Russian language in settings, only English in dropdown list.

**Comment by m417z** [comment]
Hi, thanks for the feedback. There are no translations at the moment, and the language pack suggestion is a bug that will be fixed in the next version.

**Comment by m417z** [comment]
Fixed in Windhawk v1.0. From the [changelog](https://ramensoftware.com/downloads/windhawk_setup.exe?changelog):
> Removed the confusing suggestion to download a language pack for non-English Windows versions. Windhawk still doesn't have proper support for localization.
