### ISSUE TITLE
"Check for updates" setting is always active?

### ISSUE THREAD

**Issue by Trixlight** [ramensoftware/windhawk#128]
It looks like Windhawk will check for updates even when the setting is turned off and send a notification after system startup.
This was happening on version 1.3.1 and now on 1.4.

**Comment by m417z** [comment]
I'm not able to reproduce it. Are you using the portable or the standard version?
For the standard version:
* What's the value of `DisableUpdateCheck` under `HKEY_LOCAL_MACHINE\SOFTWARE\Windhawk\Settings`
* Is the `WindhawkUpdateTask` scheduled task enabled or disabled?

**Comment by m417z** [comment]
I believe that the issue is fixed in Windhawk v1.4.1. If not, please let me know.
