### ISSUE TITLE
Notepad darkmode doesn't work when running notepad as admin

### ISSUE THREAD

**Issue by vanbang9710** [ramensoftware/windhawk#132]
Workaround: run Windhawk as admin
Suggestion: add an option to run Windhawk as admin

**Comment by m417z** [comment]
Ate you using the portable version of Windhawk? If so, that's by design - if Windhawk isn't running as administrator, it can't customize apps running as administrator.

**Comment by vanbang9710** [comment]
I'm using the portable version. I will create a shortcut to open as admin then.

**Comment by vanbang9710** [comment]
I can open the shortcut as admin manually but when put in startup folder, it doesn't work. The normal shortcut works fine.

**Comment by m417z** [comment]
You can use Task Scheduler or a dedicated tool to auto-start Windhawk portable as administrator, but unless there's a good reason, the best solution is to just use the non-portable version.

**Comment by vanbang9710** [comment]
Could you please explain why it doesn't work with startup folder?

**Comment by m417z** [comment]
Because Windows doesn't launch startup shortcuts as administrator. You can Google for it for more information, but it's about Windows, not Windhawk.
