### ISSUE TITLE
Emulators

### ISSUE THREAD

**Issue by 111ebobo** [ramensoftware/windhawk#158]
Project 64 lags too much, and dolphin isn't running games at all

**Comment by m417z** [comment]
Do you see the issues even when all mods are disabled? Can you provide simple steps to reproduce the problems? Also, does excluding the emulators in Windhawk's advanced settings help?

**Comment by 111ebobo** [comment]
> Do you see the issues even when all mods are disabled? Can you provide simple steps to reproduce the problems? Also, does excluding the emulators in Windhawk's advanced settings help?

To reproduce that issue you need to have enabled at least 1 mod, excluding emulators didn't help. I have tried to turn off windhawk and run emulators but it didn't help

**Comment by m417z** [comment]
> To reproduce that issue you need to have enabled at least 1 mod

Does that mean that disabling all mods makes the issue disappear?

> I have tried to turn off windhawk and run emulators but it didn't help

If turning off Windhawk didn't help then it's not related to Windhawk.

**Comment by 111ebobo** [comment]
> > To reproduce that issue you need to have enabled at least 1 mod
> 
> Does that mean that disabling all mods makes the issue disappear?
> 
> > I have tried to turn off windhawk and run emulators but it didn't help
> 
> If turning off Windhawk didn't help then it's not related to Windhawk.

But before installing windhawk everything was working fine (and on windows mods with it ) I think I should boot windows without it and tell you

**Comment by 111ebobo** [comment]
> > To reproduce that issue you need to have enabled at least 1 mod
> 
> Does that mean that disabling all mods makes the issue disappear?
> 
I actually don't know yet, but when I first tried to use windhawk I have used only one mod, and I have seen that issue (and I didn't add any other program that could affect the performance, also this issue is only for this two emulators and everything else is working fine)

**Comment by 111ebobo** [comment]
Nevermind, it actually wasn't windhawk
