### ISSUE TITLE
Windhawk doesn't run minimized when added to shell:startup

### ISSUE THREAD

**Issue by abhowitzer** [ramensoftware/windhawk#159]
Context:
I've added a shortcut to Windhawk to shell:startup.
Every time I boot my desktop, Windhawk starts and opens the main window.

Issue:
I expect Windhawk to be running minimised by default and run in the tray. Right now, I have to manually close the window after boot.

**Comment by 9000000** [comment]
I'm also looking for answers like you

**Comment by abhowitzer** [comment]
@9000000 
This is a consequence of running the portable version.

Received this feedback from the developer:
> Michael (Ramen Software) — 21/02/2024 18:07
> That's not supported. To have Windhawk run as a service, use the non-portable version. Is there a specific reason for which you need the portable version? If you prefer to use the portable version you can place a shortcut of Windhawk in the startup folder, and add the -tray-only command line flag to it.

**Comment by m417z** [comment]
Closing as the question was answered.

**Comment by mustafatoktas** [comment]
Hello @m417z  I'm using the non-portable version of Windhawk. I want Windhawk to start when the pc is turned on in the minimized state. Which file of Windhawk should I put into which file path for this? Is there anything else I should do after doing these? Like the -tary-only text, for example. How do I add the text?

**Comment by m417z** [comment]
@mustafatoktas that's not possible. Why would you want to run it in a minimized state? The original issue is about having it start minimized to tray. If that's what you're after, it should happen automatically with the non-portable version, there's no need to do anything manually.

**Comment by mustafatoktas** [comment]
@m417z Thank you for your quick answer. Yes, as you said, **WH [WindHavk]** starts working automatically when the PC is turned on. Since I couldn't see **WH** in the list of startup applications in the task manager, I thought it wasn't starting on its own when the PC started.
But it wasn't like that. It's really nice that it starts on its own. Thank you for your interest.

I also want to ask this: I am using Windows 11 Home 23H2. I want the start button to appear on the left in the taskbar, but the applications appear in the middle. Do you know of any application where I can do this? Except for Start 11 and taskbarX.

**Comment by m417z** [comment]
> I also want to ask this: I am using Windows 11 Home 23H2. I want the start button to appear on the left in the taskbar, but the applications appear in the middle. Do you know of any application where I can do this? Except for Start 11 and taskbarX.

Perhaps it's possible with Windows 11 Taskbar Styler, but it requires some experimentation. There's an issue about it here:
https://github.com/ramensoftware/windows-11-taskbar-styling-guide/issues/10

**Comment by takattowo** [comment]
hi @m417z, i created a task and it didnt work, is it because windhawk refuse to run as admin?
![image](https://github.com/user-attachments/assets/e89b8297-0b8e-4819-ad3d-9732f058fa84)

**Comment by m417z** [comment]
@takattowo, I don't know, Windhawk generally can both run as admin or not. If you're running it at startup anyway, I suggest to use the standard version which takes care of running on startup.

**Comment by whyudothis5656** [comment]
So automatically with the regular version it'll start on PC startup even if it isn't shown in the startup app list?

**Comment by m417z** [comment]
@whyudothis5656 Yes, it uses a service, you can find it in the services list in Task Manager.

**Comment by yw4z** [comment]
@m417z fyi simplewall (open source firewall app) uses a similar technique without using a service and its still portable. starts on launch and bypasses uac. it might be unnecessary if you use service only for startup process
