### ISSUE TITLE
Battlefield 2042 doesnt start when Windhawk is running

### ISSUE THREAD

**Issue by Woesch-Nich** [ramensoftware/windhawk#169]
I don't know if that's something that could be changed on your side or if it's BF2042 Anti Cheat. But I use Windhawk to get the older Windows 11 Explorer back. 

Issue is: BF 2042 cant be started when running Windhawk. The moment I close, Windhawk BF2042 starts just fine. Other People have this [Issue too ](https://www.reddit.com/r/battlefield2042/comments/11tbu05/comment/krvi2tg/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button)

**Comment by m417z** [comment]
It was already reported here: https://github.com/ramensoftware/windhawk/discussions/164. My answer:

> That's probably related to the game's anti-cheat mechanism. You can exclude it in Windhawk: configure it [in the advanced settings](https://i.imgur.com/ktPDUNn.png) and add `Bf2042.exe` (or the relevant exe name or path) to the process exclusion list.

One of the users confirmed that excluding the relevant exe solved the problem.
