### ISSUE TITLE
Microsoft Games don't start with Windhawk enabled

### ISSUE THREAD

**Issue by TheColin21** [ramensoftware/windhawk#17]
I just spent hours on troubleshooting Forza Horizon 4 and 5 suddenly stop working for me. Seemingly, because Microsoft GamingServices did not work.

While I was writing an extensive bug report on the Microsoft Forums, I realized that the biggest change to my system since the games last worked was Windhawk. I closed it, the games started again.

This is a huge dealbreaker for me and probably many other gamers trying to use Windhawk.
If I can be of any assistance eliminating this error, I would be pleased to help.

**Comment by m417z** [comment]
With Windhawk v1.0, it's now possible to exclude processes in Windhawk. Please try it and let me know whether it helps.

Aside from that, it would be great if Windhawk could be compatible with Microsoft GamingServices, but it requires understanding the reason for the incompatibility. Perhaps it just refuses to run if it detects code injection, in which case Windhawk can't do much except for providing the option to avoid the injection.

Since I don't plan to investigate it in the near future, I'm closing the issue.

**Comment by aboisleux** [comment]
Hello, I ran into the same issue.
Log in Xbox app is: 
![image](https://github.com/ramensoftware/windhawk/assets/26811422/8169fabd-b220-4696-9bac-faddfde40ef5)
Error code is 0x8027025b

I've tried to exclude below processes (XboxGamingServices, and FH4 = Sunrise), without success. I have to fully close Windhawk, otherwise Forza Horizon 4 will not start.
```
<critical_system_processes>
%ProgramFiles%\WindowsApps\Microsoft.GamingApp_2312.1001.18.0_x64__8wekyb3d8bbwe\XboxGameBarWidgets.exe
%ProgramFiles%\WindowsApps\Microsoft.GamingApp_2312.1001.18.0_x64__8wekyb3d8bbwe\XboxPcApp.exe
%ProgramFiles%\WindowsApps\Microsoft.GamingApp_2312.1001.18.0_x64__8wekyb3d8bbwe\XboxPcAppFT.exe
%ProgramFiles%\WindowsApps\Microsoft.GamingServices_17.84.7001.0_x64__8wekyb3d8bbwe\gamingservicesnet.exe
%ProgramFiles%\WindowsApps\Microsoft.GamingServices_17.84.7001.0_x64__8wekyb3d8bbwe\gamingservices.exe
%ProgramFiles%\WindowsApps\Microsoft.SunriseBaseGame_1.478.564.2_x64__8wekyb3d8bbwe\ForzaHorizon4.exe
%ProgramFiles%\Electronic Arts\EA Desktop\EA Desktop\EAConnect_microsoft.exe
%ProgramFiles%\Electronic Arts\EA Desktop\EA Desktop\QtWebEngineProcess.exe
C:\Windows\System32\RuntimeBroker.exe

```

More details below (sorry, logs are in French). Here is the error in System EventViewer:

> Le serveur Microsoft.SunriseBaseGame_1.478.564.2_x64__8wekyb3d8bbwe!SunriseReleaseFinal ne s’est pas enregistré sur DCOM avant la fin du temps imparti.

 Here is the error in Applications EventViewer:
> Nom de l’application défaillante ForzaHorizon4.exe, version : 0.0.0.0, horodatage : 0x655e23b5
> Nom du module défaillant : ForzaHorizon4.exe, version : 0.0.0.0, horodatage : 0x655e23b5
> Code d’exception : 0xc0000005
> Décalage d’erreur : 0x0000000000dc2664
> ID du processus défaillant : 0x0x11D4
> Heure de début de l’application défaillante : 0x0x1DA3CDF73C32DF8
> Chemin d’accès de l’application défaillante : C:\Program Files\WindowsApps\Microsoft.SunriseBaseGame_1.478.564.2_x64__8wekyb3d8bbwe\ForzaHorizon4.exe
> Chemin d’accès du module défaillant: C:\Program Files\WindowsApps\Microsoft.SunriseBaseGame_1.478.564.2_x64__8wekyb3d8bbwe\ForzaHorizon4.exe
> ID de rapport : f8b760ec-38d7-4fd8-9825-12b580a8a22f
> Nom complet du package défaillant : Microsoft.SunriseBaseGame_1.478.564.2_x64__8wekyb3d8bbwe
> ID de l’application relative au package défaillant : SunriseReleaseFinal

**Comment by m417z** [comment]
> I have to fully close Windhawk, otherwise Forza Horizon 4 will not start.

What if you exclude all processes instead? i.e. add a line with `*` to the process exclusion list? If it helps, can you try to find out the relevant process that can be excluded to fix it? You can try with broad wildcards first, for example `%ProgramFiles%\*` and `%ProgramFiles%\Electronic Arts\*`.

> Here is the error in Applications EventViewer:

Can you capture a crash dump? You should be able to get it with the following steps:
* Open regedit
* Go to: `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\Windows Error Reporting`
* Create a key named `LocalDumps`
* Create a DWORD value named `DumpType` with value `2`
* Trigger the crash
* Go to the `%LocalAppData%\CrashDumps` folder, you should see a dump file in there

**Comment by aboisleux** [comment]
If I put below exclusion lists, Forza Horizon 4 launches 👍:
`*`

--
```
<critical_system_processes>
*
```
**-- Here it is, I've found the relevant process: ⬇️**
```
<critical_system_processes>
K:\WindowsApps\Microsoft.SunriseBaseGame_1.478.564.2_x64__8wekyb3d8bbwe\
```
⬆️
 
_For info, if I put below exclusion lists, it won't launch ⛔:_
```
<critical_system_processes>
%ProgramFiles%\*
```
--
```
<critical_system_processes>
%ProgramFiles%\*
C:\Windows\System32\*
C:\Progra~2\*
```
--

**Comment by m417z** [comment]
> **-- Here it is, I've found the relevant process: ⬇️**
> ```
> <critical_system_processes>
> K:\WindowsApps\Microsoft.SunriseBaseGame_1.478.564.2_x64__8wekyb3d8bbwe\
> ```
> ⬆️

This is a folder, did you miss the executable name or a `*` at the end?

**Comment by aboisleux** [comment]
> > **-- Here it is, I've found the relevant process: ⬇️**
> > ```
> > <critical_system_processes>
> > K:\WindowsApps\Microsoft.SunriseBaseGame_1.478.564.2_x64__8wekyb3d8bbwe\
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ⬆️
> 
> This is a folder, did you miss the executable name or a `*` at the end?

I missed the *

**Comment by m417z** [comment]
Can you try to find the exact exe file? You can check which files the folder contains and try them one by one, hopefully there aren't many.

Also, can you post a crash dump with the instructions I posted earlier?

**Comment by aboisleux** [comment]
Sorry, I don't want to send a whole crashdump. But I've followed your instructions and analyzed the dmp file with WinDbg, here is the report. I hope it helps
[FH4 Windhawk crash dump analysis.txt](https://github.com/ramensoftware/windhawk/files/13814017/FH4.Windhawk.crash.dump.analysis.txt)


I also confirm that I can use this exclusion list, and FH4 will launch:
```
<critical_system_processes>
K:\WindowsApps\Microsoft.SunriseBaseGame_1.478.564.2_x64__8wekyb3d8bbwe\ForzaHorizon4.exe
```

**Comment by m417z** [comment]
It helps, but the dump will be more helpful. It's OK if you prefer not to send it, but you can also [email it](https://ramensoftware.com/contact) directly to me so that it won't be available publicly.

Also, can you please upload the ForzaHorizon4.exe file?
