### ISSUE TITLE
"Compilation failed, the mod might require a newer Windhawk version"

### ISSUE THREAD

**Issue by ian-battaglia** [ramensoftware/windhawk#172]
Hi there,

Just learned about Windhawk, and wanted to install some mods to reduce the size of the taskbar, among others. I installed Windhawk v1.4.1 today from the official website, but when I go to install a mod, I get this error:

`Compilation failed, the mod might require a newer Windhawk version`

I don't have any antivirus on the computer aside from the default Windows security stuff, but I didn't see it flag anything. I'm also running the latest version of Windows 11, updated today. Any idea what I might be doing wrong?

**Comment by m417z** [comment]
This error message means that the compiler wasn't able to successfully compile the code, which shouldn't happen for the latest Windhawk version.

Please trigger the error, then check the following folder:
```
C:\ProgramData\Windhawk\EditorWorkspace
```
Do you have files named `compiler_errors.log`, `compiler_output.log` there? Can you post their content?

If the files are empty, that means that the error isn't a compilation error. In this case, please try to uninstall and reinstall Windhawk. Settings will be kept unless you choose to explicitly remove them while uninstalling.

If nothing of the above will help, we'll try to run the compiler manually from cmd. I'll follow up with further instructions after your update.

**Comment by m417z** [comment]
OK, let's try the following:
* Download and extract the following two files: [taskbar-icon-size-test.zip](https://github.com/ramensoftware/windhawk/files/14514223/taskbar-icon-size-test.zip)
* Open `C:\Program Files\Windhawk\windhawk.ini` and check the line starting with `EnginePath=`. If it's not `Engine\1.4.1`, then open `taskbar-icon-size-test.bat` that you extracted with Notepad, and replace `Engine\1.4.1` with the value you have in `windhawk.ini`
* Double-click on `taskbar-icon-size-test.bat`, wait until the `Press any key to continue` message is printed, and post the output.

**Comment by Thuwun** [comment]
Running compiler...
C:\Program Files\Windhawk\Compiler\bin\clang-18: Invalid argument
Compilation done: 1
Press any key to continue . . .

**Comment by Thuwun** [comment]
It is now at version 1.5.1, but I'm still getting the ...

Compilation failed, the mod might require a newer Windhawk version

error

**Comment by m417z** [comment]
> C:\Program Files\Windhawk\Compiler\bin\clang-18: Invalid argument

This means that the compiler executable is missing. Perhaps it was removed by your antivirus. Check out the previous discussion about it here:
https://ramensoftware.com/windhawk-mods-for-the-windows-11-taskbar/comment-page-3#comment-15248

The solution is to make sure the antivirus doesn't detect the file, either by updating the definitions or by adding Windhawk to the exclusions, and then to run the Windhawk setup again and choose "Reinstall".

**Comment by KitsuIllustro** [comment]
even though antivirus is deactivated. I am getting the same problem

**Comment by m417z** [comment]
@KitsuIllustro Are there any additional logs? Post the screenshot of the full Windhawk window when the error appears. Also:
* Do you have the following file? `C:\Program Files\Windhawk\Compiler\bin\g++.exe`
* Are you using an antivirus?

**Comment by sneakyjoeru** [comment]
Same issue
