### ISSUE TITLE
Isn't compatible with cargo

### ISSUE THREAD

**Issue by Krysl** [ramensoftware/windhawk#179]
> ## [Windhawk isn't compatible with a specific program](https://github.com/ramensoftware/windhawk/wiki/Troubleshooting#windhawk-isnt-compatible-with-a-specific-program)
> 
> Some programs are incompatible with Windhawk or with code injection in general. These programs can be added to Windhawk's exclusion list:
> 
> -   Open Windhawk.
> -   Go to Settings.
> -   Expand the **Advanced settings** section.
> -   Click on **More advanced settings**.
> -   Add the incompatible process to the **Process exclusion list**.
> -   Finally, click on **Save and restart Windhawk**.
> 
> If the program isn't known to be incompatible with Windhawk, please report the incompatibility [here](https://github.com/ramensoftware/windhawk/issues).

**Before** *Add the incompatible process to the **Process exclusion list***:
(the command line is broken)
```
C:\Windows\System32
# cargo --version

C:\Windows\System32
#
```
**After** *Add the incompatible process to the **Process exclusion list***:
```
C:\Windows\System32
# cargo --version
cargo 1.77.2 (e52e36006 2024-03-26)

C:\Windows\System32
#
```

**Comment by m417z** [comment]
Hi, sorry for the late reply.
I installed Rust with the default configurations, and it seems to work with Windhawk for me:
```
C:\Users\User>cargo --version
cargo 1.78.0 (54d8815d0 2024-03-26)
```
Could it be related to one of the installed mods you have?
Or perhaps something changed between 1.77.2 and 1.78.0?

**Comment by Krysl** [comment]
Weird, I can't reproduce it, even if I reinstall version 1.77.2.
Maybe something has changed, but I can't find it for a while.
I'm closing this issue for now. If I can reproduce the problem later, I'll reopen it.
Thank you for your patience.
