### ISSUE TITLE
Settings after drive corruption.

### ISSUE THREAD

**Issue by SaiMorphX** [ramensoftware/windhawk#194]
I'm trying to figure out where windhawk saves mod settings. I recently tried to upgrade my cpu but got a faulty one, and it corrupted the boot loader, so I installed windows on another drive and can retrieve files from the other drive for now. BUT WHERE!!! If I recall I had only 2 mods, and only one was really used, but I'd like to get those settings so I don't have to try and recreate them.

Thanks for any help with this.

**Comment by SaiMorphX** [comment]
I found it looking in the software hive file. This really makes moving this from system to system, a give up on windhawk task. signal rgb, I could move my files over.... .... I loved windhawk, maybe I can setup some generic junk, and copy this over.

![windhawk_regsave](https://github.com/ramensoftware/windhawk/assets/8024376/6598a6c5-b270-4515-a5df-defa0f3302e4)

**Comment by SaiMorphX** [comment]
> Mod settings can be found in:
> 
> ```
> HKEY_LOCAL_MACHINE\SOFTWARE\Windhawk\Engine\Mods\<mod-id>\Settings
> ```
> 
> If what you need is settings, the easiest way to migrate would be to install the three mods, and then copy the settings from the Settings registry key.
> 
> The cache entry in `LocalSettings` in your screenshot isn't necessary, it will be recreated automatically by Windhawk.

Thank you! sucks I tried to just export them to a reg file and install them to the register, but when I started Windhawk again they were all still set at default.

Hey, at least I have the information!

**Comment by m417z** [comment]
As far as I understand, you managed to get it working, or at least have the necessary info. I'm closing the issue. If you need more help, feel free to follow up.
