### ISSUE TITLE
show not revert the bottom icon of start menu while using 【SideBySide2】 [Windows 11 Start Menu Styler]

### ISSUE THREAD

**Issue by heartacker** [ramensoftware/windhawk#203]
- normal or default
![SideBySide or normal](https://github.com/ramensoftware/windows-11-start-menu-styling-guide/raw/main/Themes/SideBySide/screenshot.png)

- SideBySide2
![SideBySide2](https://github.com/ramensoftware/windows-11-start-menu-styling-guide/raw/main/Themes/SideBySide2/screenshot.png)

**Comment by heartacker** [comment]
![image](https://github.com/ramensoftware/windhawk/assets/1876302/57ee3cef-9945-4221-98b2-086f071340b9)

**Comment by m417z** [comment]
That's how the author of the theme, @dreamsynth, designed it, so it's not a bug. It was discussed here:
https://github.com/ramensoftware/windows-11-start-menu-styling-guide/issues/18
https://github.com/ramensoftware/windows-11-start-menu-styling-guide/issues/21
