### ISSUE TITLE
Windhawk blocks start of Office app (Outlook, Word, Excel...)

### ISSUE THREAD

**Issue by Tux3094** [ramensoftware/windhawk#204]
Windhawk blocks start of Office app (Outlook, Word, Excel...). It somehow is connected to "AppVIsvSubsystems64.dll". Windows event log shows an application error on startup of Office Apps. See the Reddit thread: [https://www.reddit.com/r/Office365/comments/1de5nma/help_office_completely_broken/](url)

Shutting down windhawk "resolves" the problem.  :-/

**Comment by jsarnold** [comment]
Experiencing the same problem.

**Comment by m417z** [comment]
It’s a known issue. I haven’t had the chance to look at it yet, but for now, you can add office to the exclusion list, see:
https://github.com/ramensoftware/windhawk/issues/198#issuecomment-2169560663

Thanks for reporting. Closing as a duplicate.
