### ISSUE TITLE
Exclude all processes except specific ones

### ISSUE THREAD

**Issue by m3dragos** [ramensoftware/windhawk#215]
Current behavior for including/excluding processes is described as:
`"For each process, the mod is loaded if the executable file path matches one of the include entries and doesn't match any exclude entry."`

It seems that it's not possible to exclude all processes _except_ specific ones.
As the text says, and as it seems to work now, if I have `*` in the exclusion list then all processes are excluded, ignoring the inclusion list. Also if I only populate the inclusion list nothing changes, they were all included by default anyway?

I would expect that if I put `*` in the exclusion list (or leave it empty) and add a specific process in the inclusion list, that process would be included and all others excluded.

Current behavior, with these settings, **all** processes are excluded:
![image](https://github.com/ramensoftware/windhawk/assets/17458988/0b086d98-b83d-48ef-9e4a-2e18e506fe89)

Current behavior, with these settings, **all** processes are included:
![image](https://github.com/ramensoftware/windhawk/assets/17458988/3aad47f3-1a1d-4973-8edf-ef5a422d807c)

**Comment by m417z** [comment]
> Also if I only populate the inclusion list nothing changes, they were all included by default anyway?

The default is whatever the mod defines. Which mod are you trying to customize. If the mod targets all or multiple programs, then indeed what you said is correct, but you can find an option that says "Ignore mod inclusion/exclusion lists" below. If you enable it, then the mod's targets are ignored, and you can add only the processes you want to the process inclusion list.

**Comment by m3dragos** [comment]
I'm trying this with the `taskbar-labels` mod. 
But I get the exact same behavior with the 'Ignore' option

**Comment by m417z** [comment]
`taskbar-labels` only targets explorer.exe. You're probably trying to make it so that only some apps have labels, but it doesn't work that way. See this comment and the relevant issue for more information: https://github.com/ramensoftware/windhawk-mods/issues/203#issuecomment-1927180436
