### ISSUE TITLE
windows 11 search function not working after installing windhawk

### ISSUE THREAD

**Issue by mefferr** [ramensoftware/windhawk#224]
After installing Windhawk and enabling some mods I noticed that the search functionality stopped working. When I open the Start menu and attempt to use the search feature, it doesn't work. Typing in the Start menu only highlights apps based on the letters pressed, rather than triggering a search as it used to before. When clicking on the search bar, the Start menu briefly disappears, reappears for a split second and then permanently disappears again. The search icon on the taskbar is also not working.

I have tried every fix tutorial on the internet and nothing worked so far. 

also created a new user in my windows 11 system and when i switch to it everything works just fine even when windhawk is working with mods enabled. So yeah i have no idea what caused this.

**Comment by mefferr** [comment]
fixed by finding the settings app -> right clicking on it -> app settings -> Repair

**Comment by kodo777** [comment]
![image](https://github.com/user-attachments/assets/e24e2be1-0866-4373-bc7b-c06a1547b62a)

Only uninstall is listed in the settings app, am I missing something?

**Comment by m417z** [comment]
It was reported that the "Clean up UWP processes" mod can cause this problem. Are you using it?

**Comment by kodo777** [comment]
Ah yep, disabling that does the trick, cheers
