### ISSUE TITLE
Windhawk 1.5 suggests update to version 1.5

### ISSUE THREAD

**Issue by Anixx** [ramensoftware/windhawk#237]
The About dialog suggests update even though the update is already installed.

**Comment by m417z** [comment]
The latest version is 1.5.1. Can you show where it suggests 1.5 again?

**Comment by Anixx** [comment]
It brings to the download page https://windhawk.net/download?version=1.5

**Comment by m417z** [comment]
What's wrong about that? Maybe the confusion is about the URL, `version=1.5` is your current version, maybe I should change it to `current_version`...

**Comment by m417z** [comment]
LMK if there's still an issue.
