### ISSUE TITLE
Windhawk starts with a blank document and "Untitled-1" title

### ISSUE THREAD

**Issue by HMwancheng** [ramensoftware/windhawk#242]
![image](https://github.com/user-attachments/assets/47064ccb-6692-423c-9f4c-810da86ff74c)

**Comment by HMwancheng** [comment]
can't open the normal pannal
even restart

**Comment by HMwancheng** [comment]
![image](https://github.com/user-attachments/assets/b9348eb9-74da-443a-879e-f3d7a17cf6e6)
reboot also

**Comment by m417z** [comment]
Is it still an issue?

Please try removing this folder: `C:\ProgramData\Windhawk\UIData`

If it doesn't help, try reinstalling Windhawk.

Let me know if it's still an issue after these steps.

Also, I'd like to have it fixed, so if you have steps to reproduce it, let me know. If it just happened randomly, then I'm afraid I don't have much to do at this point, but I'll keep an eye on it.
