### ISSUE TITLE
Running Windows Installer on Wine Linux is failed

### ISSUE THREAD

**Issue by GermanAizek** [ramensoftware/windhawk#245]
@m417z, not working windows installer on Wine (socket failure during downloading assets).

![изображение](https://github.com/user-attachments/assets/329bf6e9-7916-44b5-b7a6-db98af94755c)

**Comment by m417z** [comment]
Wine is not supported, I'd be very surprised if Windhawk worked even to some degree in Wine. Most mods have zero chance of working as they're tailored for Windows executables. Windhawk itself also does many assumptions around Windows internals, which I'm not sure Wine replicates in such detail.

Regarding the error you saw - the installer was unable to download the required dependencies. The installer uses [the Inetc plug-in](https://nsis.sourceforge.io/Inetc_plug-in), not sure why it doesn't work in Wine. As the message says, you can download an offline installer and try it.

**Comment by GermanAizek** [comment]
@m417z, offline installer is really better for installation on Linux Wine, but why is there access to socket if it is offline installer?
![изображение](https://github.com/user-attachments/assets/3eee37a2-4523-49af-8411-d99599cc103d)

**Comment by m417z** [comment]
Where do you see the word "socket"? Error 1053 means: The service did not respond to the start or control request in a timely fashion.

Maybe the service crashed or something. Not surprising. As I said, Windhawk wasn't designed for Wine. If you have a crash dump or log, I can take a look, but don't plan on investigating it.

**Comment by GermanAizek** [comment]
> Where do you see the word "socket"?

Indeed, I accidentally said wrong thing. I can try Portable installation, but is there no way to download ready-made archive with binaries?

**Comment by m417z** [comment]
No. You can run it with `/portable` if that helps. You can extract it on Windows and copy the files to Wine.

**Comment by GermanAizek** [comment]
> No. You can run it with `/portable` if that helps. You can extract it on Windows and copy the files to Wine.

Well, it didn't work out to launch Portable :(

![изображение](https://github.com/user-attachments/assets/cf399727-0082-469c-9c72-841e7ac076ff)

**Comment by m417z** [comment]
You can try enabling logs: Set `LoggingVerbosity=2` in `AppData\settings.ini` and in `AppData\Engine\settings.ini`, then use DebugView or a similar program.
