### ISSUE TITLE
Windhawk IDE does not start if Windhawk service is running

### ISSUE THREAD

**Issue by Anixx** [ramensoftware/windhawk#264]
Windhawk IDE does not start when Windhawk service is running. If I stop the service, the IDE starts. This happens even if ALL mods are disabled.

If to exclude VSCodium.exe in the Windhawk settings, the IDE starts well.

This issue emerged today without any visible cause.

**Comment by m417z** [comment]
Does the IDE crash? You can look for crashes in the event viewer. Open Event Viewer, and check [Windows Logs](https://download.cyberlink.com/ftpdload/cs/faq_pic/General/ENU/event_log_02.png).

**Comment by Anixx** [comment]
The issue went away after reboot.
