### ISSUE TITLE
I can't download Windhawk

### ISSUE THREAD

**Issue by ployyka** [ramensoftware/windhawk#286]
I’m trying to download the application, I confirm as an administrator, I do everything, it loads, but on the very first program for downloading it doesn’t want to. and says that there are problems with the Internet, but I have 5G Internet, I installed it myself, and nothing happens. What to do?

**Comment by m417z** [comment]
Please provide more details. Is there an error while trying to browse for mods? What do you see? What's the exact error message?
A screenshot or screen recording will help as well.

If you're using a proxy, that might be the same issue as https://github.com/ramensoftware/windhawk/issues/134.

**Comment by sourvinos** [comment]
1. Go here: https://windhawk.net
2. Click on 'download'. (Blue button, the first of three blue buttons)
3. After some time this page is shown:

This site can’t be reached
ramensoftware.com took too long to respond.

4. I don't use a proxy.

**Comment by m417z** [comment]
@sourvinos I tried it on several computers/networks and it works for me. Does https://ramensoftware.com/ return the same error?
Meanwhile you can download Windhawk from GitHub:
https://github.com/ramensoftware/windhawk/releases/latest

@ployyka are you getting the same error?

**Comment by ployyka** [comment]
> @sourvinos I tried it on several computers/networks and it works for me. Does https://ramensoftware.com/ return the same error? Meanwhile you can download Windhawk from GitHub: https://github.com/ramensoftware/windhawk/releases/latest
> 
> @ployyka are you getting the same error?

yes, I tried download from Github and I got the same error...

**Comment by ployyka** [comment]
> Please provide more details. Is there an error while trying to browse for mods? What do you see? What's the exact error message? A screenshot or screen recording will help as well.
> 
> If you're using a proxy, that might be the same issue as #134.

no, during the download itself everything stops for me, referring to the fact that when downloading the first “plugin?” An error appears - that this 7zip cannot be downloaded, because supposedly there is no Internet

i dont use a proxy, i use my home network (Wi-Fi). trying use my mobile services network - nothing works either

**Comment by ployyka** [comment]
AND!! when I wanted to take a screenshot (literally 2 minutes ago), a bug prevented me from doing so, breaking the taskbar. That is, the settings panel did not work (on/off Wi-Fi, Bluetooth, airplane mode, volume, etc.) and the calendar did not open with time and notifications. Only a reboot helped restore everything

**Comment by ployyka** [comment]
It seems that I really used the system proxy server... I deeply apologize!

**Comment by ployyka** [comment]
i think, using the telegram I did something that caused everything to break...

**Comment by m417z** [comment]
You can try using the offline installer which doesn't download additional dependencies during installation. You can get it here:
https://github.com/ramensoftware/windhawk/releases/latest

**Comment by ployyka** [comment]
> You can try using the offline installer which doesn't download additional dependencies during installation. You can get it here: https://github.com/ramensoftware/windhawk/releases/latest

im download this\

**Comment by psychowrld12** [comment]
i have tired all the methods til not working

**Comment by m417z** [comment]
@psychowrld12 have you downloaded the offline installer? What's the problem? Are you getting an error message?
