### ISSUE TITLE
install Windhawk modes silently using terminal

### ISSUE THREAD

**Issue by akamienski** [ramensoftware/windhawk#311]
Hello,

I would like to install Windhawk itself (using winget) and the modes automatically and silently, without any user interaction. Is it currently possible?

Gonfiguring them isn't necessary, as this can be achieved with registry edit.

**Comment by m417z** [comment]
Currently it's not possible. It's planned and is tracked here: https://github.com/ramensoftware/windhawk/issues/154.
For now, the closest thing you might find useful is manually importing installed mods: https://github.com/ramensoftware/windhawk/discussions/155.
