### ISSUE TITLE
Toggles to make Windhawk start with Windows and minimized to tray

### ISSUE THREAD

**Issue by LOuroboros** [ramensoftware/windhawk#328]
Hi!

I found Windhawk a few days ago after I formatted my PC when I found some issues with ExplorerPatcher that made me look for alternatives to customize my system's appearance and basic Windows Explorer functionality.

I stumbled upon Windhawk and it's been a comfortable program to use thus far, but to my surprise, the program's settings are kinda barebones.

So, since you have to open Windhawk in order for its modifications to take effect, I was thinking it could be a good idea to suggest to update it with a few configuration toggles, more specifically one to make the program start with Windows, and another one to make it start minimized to tray. Nice and silent, without showing up on the desktop and making the user close the window.

**Comment by m417z** [comment]
> [...] make the program start with Windows, and [...] make it start minimized to tray. Nice and silent, without showing up on the desktop and making the user close the window.

Hi, Windhawk works the way you describe if you're using the standard installation. I assume that you're using the portable installation, in which case you'll need to set it up to run at startup manually. See also the discussion here: https://github.com/ramensoftware/windhawk/discussions/5.

**Comment by LOuroboros** [comment]
> > [...] make the program start with Windows, and [...] make it start minimized to tray. Nice and silent, without showing up on the desktop and making the user close the window.
> 
> Hi, Windhawk works the way you describe if you're using the standard installation. I assume that you're using the portable installation, in which case you'll need to set it up to run at startup manually. See also the discussion here: #5.

Thanks! I certainly do use the portable version, and the `-tray-only` argument is exactly what I needed after having dropped a shortcut in Windows' Startup folder.
It'd be nice if that argument, and other potentially useful arguments, were mentioned somewhere. Perhaps in an article at the Wiki for example.

**Comment by m417z** [comment]
There's the `command-line.txt` file that I added to the Windhawk folder at some point, hoping that while creating the shortcut manually, you'll open the folder to locate the executable, and this file will grab your attention. It didn't work in your case. Do you think it'd be more likely for you to find about it in the wiki then to see that file or to find [one of the previous threads](https://www.google.com/search?q=windhawk+start+hidden) in Google?

**Comment by LOuroboros** [comment]
> There's the `command-line.txt` file that I added to the Windhawk folder at some point, hoping that while creating the shortcut manually, you'll open the folder to locate the executable, and this file will grab your attention. It didn't work in your case. Do you think it'd be more likely for you to find about it in the wiki then to see that file or to find [one of the previous threads](https://www.google.com/search?q=windhawk+start+hidden) in Google?

Before making this Issue ticket I first went to the wiki, and it didn't really occur to me to search about this super specific thing related to a program I had just learned about on Google to be honest.

**Comment by m417z** [comment]
I created [a wiki page](https://github.com/ramensoftware/windhawk/wiki/Command-line-flags) for it.

**Comment by adi-works** [comment]
@m417z Does the non-portable version initiates the UI seamlessly? the main con with the portable version is that `shell:startup` is a low priority feature, so the default UI appears until then, which is quite annoying.

**Comment by m417z** [comment]
@adi-works I'm not sure what you mean by "initiates the UI seamlessly", but the non-portable version starts earlier, and is generally recommended for regular usage.

**Comment by adi-works** [comment]
Picked the wrong wording, but yes, that's what I meant. I ended up using the non-portable version and now it injects itself earlier, so there's no flash of the default taskbar UI before it swaps to the new one.
