### ISSUE TITLE
Server error: authenticationrequired

### ISSUE THREAD

**Issue by mho-de** [ramensoftware/windhawk#33]
When I run Windhawk and try to browse/explore the mods, the above mentioned error message is displayed while the main window of Windhawk shows "Loading Failed".
My internet connection is being realized via a proxy server and a VPN. All other applications I use, such as browsers or email programs, can connect to the internet just fine without any special settings.

**Comment by m417z** [comment]
Windhawk tries to download the mods catalog from https://mods.windhawk.net/catalog.json, which is served by Cloudflare as a CDN provider. Cloudflare does some access control to protect from misuse such as DDOS, and perhaps your IP was flagged for some reason. Can you browse to the catalog from the browser?

**Comment by mho-de** [comment]
Thanks for the reply. 
   
  
    Yes, I can browse to the catalog with my browser from this PC: 
   
   
    
   
  
      
   
  
    So I guess it is our Proxy settings or Firewall that prevents Windhawk from accessing it. There are a few other applications that cannot connect to the internet when running on one of our PCs. At home, with regular direct internet access and more liberal Firewall settings, everything works just fine. 
   
  
      
   
   
   
     Michael Maltsev ***@***.***> hat am 04.01.2023 15:51 CET geschrieben: 
    
   Windhawk tries to download the mods catalog from https://mods.windhawk.net/catalog.json, which is served by Cloudflare as a CDN provider. Cloudflare does some access control to protect from misuse such as DDOS, and perhaps your IP was flagged for some reason. Can you browse to the catalog from the browser?

**Comment by m417z** [comment]
> There are a few other applications that cannot connect to the internet when running on one of our PCs.

In this case, it sounds like an issue unrelated to Windhawk. Closing. Let me know if there are any other insights regarding ways Windhawk can improve here.
