### ISSUE TITLE
Virustotal Says Windhawk has a Trojan

### ISSUE THREAD

**Issue by tigintexas** [ramensoftware/windhawk#355]
Virustotal says Windhawk has Trojan.Downloader.gen
Please advise.

**Comment by m417z** [comment]
It was discussed in the past. The last issue on the topic was https://github.com/ramensoftware/windhawk/issues/291.

> These are false positive detections. Unfortunately, struggling with false positives is a non-ending hassle.
> This problem was discussed before, e.g. https://github.com/ramensoftware/windhawk/discussions/223, and also in the blog comments regarding my tools, for example: [1](https://ramensoftware.com/7-taskbar-tweaker/comment-page-43#comment-11035), [2](https://ramensoftware.com/contact/comment-page-4#comment-10292).
> See also Nir Sofer's blog post, [Antivirus companies cause a big headache to small developers](https://blog.nirsoft.net/2009/05/17/antivirus-companies-cause-a-big-headache-to-small-developers/), a good write-up about the problem.
> 
> You can always help by reporting the detection as a false positive to the relevant antivirus companies.
