### ISSUE TITLE
How to submit a new module?

### ISSUE THREAD

**Issue by easyatm** [ramensoftware/windhawk#356]
[https://github.com/easyatm/windhawk_mod/blob/master/win-d-per-monitor.cpp](https://github.com/easyatm/windhawk_mod/blob/master/win-d-per-monitor.cpp)

**Comment by m417z** [comment]
Please refer to the readme here:
https://github.com/ramensoftware/windhawk-mods?tab=readme-ov-file#submitting-a-new-mod

Let me know if you need more help.

**Comment by easyatm** [comment]
Okay, I'm not very familiar with Git collaboration operations, I'll look into it.
