### ISSUE TITLE
When editing the source code, use the existing .clang-format file.

### ISSUE THREAD

**Issue by easyatm** [ramensoftware/windhawk#357]
I'm not used to the built-in formatting of .clang-format, and when I modify the configuration, the next time I edit the source code, it will revert to the default configuration. When I set the .clang-format file to read-only, the source code editor will report an error. Is it possible to modify the creation logic of this file? If the .clang-format file exists, can it be prevented from being created?

**Comment by m417z** [comment]
Have you tried looking at the file content? It says:

> `# To override, create a .clang-format.windhawk file with the desired settings.`

Just create the `.clang-format.windhawk` file. In case this file exists, it will be used for `.clang-format` instead of the default predefined style.

**Comment by easyatm** [comment]
Ah... So that's how it is, I didn't notice the text in the comments above.
