### ISSUE TITLE
Registering windhawk as a service to achieve automatic startup failure

### ISSUE THREAD

**Issue by sunny-00001** [ramensoftware/windhawk#363]
Windhawk realizes boot self-startup priority by registering as a service，But when I use the command: “sc create WindhawkService binPath=C:\Program Files\windhawk\windhawk,exe” After registration service starts，hint Error 1053: The service did not respond to the start or control request in a timely fashion 
How can I correctly implement the service startup?

**Comment by m417z** [comment]
Using the cs command with Windhawk is not necessary and not supported. The standard Windhawk version installs the service which runs on startup automatically. The portable Windhawk version isn't designed to run as a service.
