### ISSUE TITLE
WINDHAWK STOP WORK

### ISSUE THREAD

**Issue by RAZLASASZ** [ramensoftware/windhawk#37]
Hi. 
Since the last update in windows system, Windhawk platform stops work in my system. 
I have Windows 10 Pro, 19045.2546 stable compilation, 22H2 version.

I speak with support in the mod Taskbar Clock Customization from Windhawk platform, and It said me in this mod>>>

The problem is that Microsoft didn't publish debug symbols for this version of explorer.exe. Hopefully they'll publish the missing symbols in the following days. Unfortunately I don't have control over this, so your options are either wait or downgrade to the previous version by removing the latest Windows update.

I do not know if Windhawk platform stop work in my system for the same problem with the mod Taskbar Clock Customization in this platform, because all mods not work in my system right now. 
[Windhawks Taskbar Clock Customization Support conversation.txt](https://github.com/ramensoftware/windhawk/files/10498024/Windhawks.Taskbar.Clock.Customization.Support.conversation.txt)

Wait for your response.
Kind Regards.

**Comment by m417z** [comment]
What do you mean by "Windhawk platform stops work in my system"? What exactly doesn't work? Are you seeing any error messages? Which mods have you tried?

**Comment by RAZLASASZ** [comment]
Because after update my Windows system to the last stable 22H2 version, some mods I use in this platform stops work in my system, 
I use this mods in Windhawk platform:
- Chrome/Edge scroll tabs with mouse wheel
- Dark mode for Notepad
- Disable grouping in taskbar
- Ignore focus loss
- Im-mediakey-explorer-fix
- Middle click to close on the taskbar
- Slick window arrangement
- Taskbar clock customization
- Taskbar thumbnail reorder
- Taskbar volume control
- Text replace
- Timer resolution control
- Visual Studio anti-reach-header
- Visual Studio solution icon
- VSCode tweaker

I think no-one works in my system and not works Windhawks platform in my system right now, because I know some of this mods not work in my system right now, like:
- Taskbar clock customization
- Taskbar volume control
- Ignore focus loss
- Dar mode for Notepad
etc.  

Wait for your response.
Kind Regards.

**Comment by m417z** [comment]
> some of this mods not work in my system right now

So, some mods don't work, or all mods don't work?

Can you please send debug logs, for example, for **Taskbar volume control**?

Steps, as a reminder:
• Disable the mod.
• Enable "Detailed debug logs" in the mod's Advanced tab.
• Click on "Show log output".
• Enable the mod.
• Verify that the mod doesn't work, copy the log output and send it here.

**Comment by RAZLASASZ** [comment]
I updated Windhawk platform to v1.1, and now all mods works ok. 

Thanks for the support.
Kind Regards.

**Comment by RAZLASASZ** [comment]
I close this issue.
Problem solved.
