### ISSUE TITLE
Windhawk conflict with VirtualBox

### ISSUE THREAD

**Issue by ttodua** [ramensoftware/windhawk#39]
when windhawk is running (i have "Middle click to close " mod running ( with "old explorer support" option checked),
then it conflicts virtualbox and we can't boot up any Windows guest OS boxes:
```
b64.3058: Error -5637 in supR3HardNtChildPurify! (enmWhat=5)
b64.3058: supHardenedWinVerifyProcess failed with -5637: NtQueryVirtualMemory failed for 0000000000000000: 0xc000010a
b64.3058: supR3HardNtEnableThreadCreationEx:
```

After exiting WindHawk, virtualbox works well.

I know this might not be priority, but just giving note to you about this issue.

**Comment by m417z** [comment]
A duplicate of https://github.com/ramensoftware/windhawk/issues/25

From the issue above:
> this failure is due to unsigned code injection being detected in the VM host process, so VirtualBox refuses to start the VM

The best solution is to exclude VirtualBox in the advanced settings of Windhawk. Let me know if you need help with that.

**Comment by ttodua** [comment]
Thanks, I will try that
