### ISSUE TITLE
Adding Windhawk Portable to Startup folder causes windows open Windhawk's GUI every startup

### ISSUE THREAD

**Issue by vanbang9710** [ramensoftware/windhawk#40]
I'm doing as your [suggestion here](https://hyp.is/XRrQsp5PEe2rCe96oZXJ9g/ramensoftware.com/windhawk).

The expected behavior: Every startup, WIndhawk only runs in system tray without displaying its GUI like the non portable version

**Comment by m417z** [comment]
Your link doesn't work without an extension. In any case, [as written here](https://ramensoftware.com/windhawk#comment-13938), you can add the `-tray-only` command line switch to the shortcut in the Startup folder.

**Comment by vanbang9710** [comment]
Thank you, it works!
