### ISSUE TITLE
I upgraded to v1.2 and about still shows v1.1

### ISSUE THREAD

**Issue by DSeiford** [ramensoftware/windhawk#45]
I have Windhawk installed on two computers. The first one is not running the Windows Insider builds and I was prompted to update Windhawk. I did the update and it now shows v1.2

The second computer is running the Release Preview channel. It has two issue. First, when I installed the v1.2 update, it still shows v1.1 as the version number.

My second issue is that Taskbar Labels for Windows 11 mod hasn't worked since the latest Windows update. I'll post that issue in the mods section.

**Comment by m417z** [comment]
> it still shows v1.1 as the version number.
That's a bug. You can check that it's indeed v1.2 by looking at the available languages in settings. If there's only English, it's v1.1. If there are other language, it's v1.2, even if the about page says v1.1.

> Taskbar Labels for Windows 11 mod hasn't worked since the latest Windows update

That's a known issue, unrelated to v1.2. Microsoft seemed to make some significant taskbar-related changes in this version. I'll look at it soon.

![image](https://user-images.githubusercontent.com/4129781/222069461-f5970149-54af-4ba9-829e-687b5d15cef9.png)

**Comment by DSeiford** [comment]
I can confirm that I see multiple languages in settings. Thanks for looking into this. The one thing I really miss from Windows 10 is the taskbar labels. I used to use Start11, but the latest update broke Start11 as well.

**Comment by DSeiford** [comment]
I updated the Taskbar Labels for Windows 11 module to the new version, and it now works with the Moments update. Windhawk still shows v1.1 instead of 1.2. That is only cosmetic and should not be a priority to fix.

**Comment by DSeiford** [comment]
The latest Windows update in the preview channel of Windows broke the taskbar labels and grouping features again. I've selected to be removed from the Insider program on the next release. I appreciate you trying to keep up with Microsoft making all those changes.

**Comment by m417z** [comment]
Windhawk version 1.3 was released, and the incorrect version number is no longer a problem.
