### ISSUE TITLE
Changing the interface language

### ISSUE THREAD

**Issue by D1mar0n** [ramensoftware/windhawk#65]
Hello! I unpacked the portable version, I see the presence of the Russian language file in "Windhawk\UI\locales/", but there is no way to select this language in the program settings. How to fix it? Thank you in advance for your response.

**Comment by m417z** [comment]
Hello, the folder that you found doesn't contain Windhawk translations. Windhawk translations can be found here:
https://github.com/ramensoftware/windhawk-translate
To have Russian or any other missing language available for selection, somebody has to contribute a translation. If you can contribute a Russian translation, that would be great.

**Comment by D1mar0n** [comment]
Thank you very much for your answer! I was very surprised to get a response so quickly. I'll see what I can do about the transfer over the weekend. Thanks for the program and all the best!
На Вт.11.04.2023 16:56:00, Michael Maltsev ***@***.***> написал(а):
Hello, the folder that you found doesn't contain Windhawk translations. Windhawk translations can be found here:
https://github.com/ramensoftware/windhawk-translate [https://github.com/ramensoftware/windhawk-translate]
To have Russian or any other missing language available for selection, somebody has to contribute a translation. If you can contribute a Russian translation, that would be great.
