### ISSUE TITLE
Windhawk taskbar button has no context menu

### ISSUE THREAD

**Issue by Anixx** [ramensoftware/windhawk#66]
Which makes it complicated to close the window, exit application without switching to it.

**Comment by m417z** [comment]
Use the [Middle click to close on the taskbar](https://windhawk.net/mods/taskbar-button-click) mod :)

More seriously, the Windhawk UI is based on VSCode, and it inherits this limitation from it. VSCode inherits this limitation from Electron. The Electron team [said they're not interested in developing it](https://github.com/electron/electron/issues/12134). It would be nice to have a classic menu, but it's not easy to add it and I don't plan working on Electron for this in the near future.

**Comment by m417z** [comment]
Closing as I don't plan working on it.
