### ISSUE TITLE
Web contents turns gray when clicking anything that isn't a button

### ISSUE THREAD

**Issue by Cynosphere** [ramensoftware/windhawk#69]
![VSCodium_04-15-23_11-10-26](https://user-images.githubusercontent.com/1606710/232241770-8cba3624-fe68-4ef5-ac25-a951b40fbeec.gif)
![image](https://user-images.githubusercontent.com/1606710/232241824-1c0598b6-c29b-4102-a634-aaf012bb3342.png)

Fixed by reopening the window. Makes it impossible to edit settings/exclusions as clicking the tab causes it to go gray.

**Comment by m417z** [comment]
I suspect that one of your mods causes this. Please try disabling all the mods and report whether it helps. Here's a similar report with a resolution from the Windhawk Discord channel:

![image](https://user-images.githubusercontent.com/4129781/232242025-72dca47c-70f9-4ee0-bdde-025e471f89a1.png)
