### ISSUE TITLE
Windhawk.exe process does not exit when closing the IDE window

### ISSUE THREAD

**Issue by Anixx** [ramensoftware/windhawk#70]
I have to go to Task Manager to kill it...

**Comment by m417z** [comment]
The IDE window isn't run by windhawk.exe, it's run by VSCodium.exe. When you kill windhawk.exe, you either kill the tray icon process or the service. To exit Windhawk cleanly, right click on the tray icon and click Exit.

![image](https://user-images.githubusercontent.com/4129781/232401868-540178fa-540a-4254-8a14-fb2d1fbc1e11.png)
