### ISSUE TITLE
Software Copyright

### ISSUE THREAD

**Issue by looluo** [ramensoftware/windhawk#78]
I wish to use this software on the Windows machines within my company, but I am unable to locate a detailed definition of the copyright information for this software. 
I would like to request a detailed copyright information to confirm if it is permissible to use this software within my company.

**Comment by m417z** [comment]
It's a freeware software which you can use on within your company. I don't have detailed copyright information and don't work with a lawyer. Let me know if there's anything else I can help with.

**Comment by looluo** [comment]
@m417z  Think you for the explaination.
