### ISSUE TITLE
Windhawk VirtualBox incompatibility

### ISSUE THREAD

**Issue by LoboMetalurgico** [ramensoftware/windhawk#94]
If you try to start a virtualbox virtual machine with windhawk active it will refuse to start.

Workaround: Enabling Windhawk Safe-Mode While Using VM

I recommend creating a "program exceptions list" that Windhawk simply won't try to inject anything into, so you don't have to turn off all extensions while you use a vm.

**Comment by m417z** [comment]
It's a known incompatibility and there is such a list, see https://github.com/ramensoftware/windhawk/issues/25

Let me know if you need help with the exclusion list.

**Comment by LoboMetalurgico** [comment]
I am unable to locate it. How can I add VB to it?

**Comment by m417z** [comment]
You can configure it [in the advanced settings](https://i.imgur.com/ktPDUNn.png). You can add the VirtualBox executable name, or path such as `%ProgramFiles%\Oracle\VirtualBox\*`, to the exclusion list.

**Comment by LoboMetalurgico** [comment]
I just did this, thanks for your help and sorry for the blindness of not seeing the fixed issue.
